services:
  - type: web
    name: django-web
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn kuruwa_backend.wsgi:application"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: kuruwa_backend.settings
      - key: SECRET_KEY
        generateValue: true
